/* Taketori - Make Text Vertical 
 * Copyright 2010-2011 CMONOS. Co,Ltd (http://cmonos.jp)
 *
 * Version: 1.3.0
 * Lisence: MIT Lisence
 * Last-Modified: 2012-04-06
 */
var TaketoriVersionForMuse={ver:"r8"},TaketoriDblClickAlert={"ja-jp":"\ufeff\u7e26\u66f8\u304d\u5316\u3057\u305f\u3044\u90e8\u5206\u3092\u30c0\u30d6\u30eb\u30af\u30ea\u30c3\u30af\u3057\u3066\u304f\u3060\u3055\u3044\u3002","zh-tw":"\u9ede\u5169\u4e0b\u4ee5\u5207\u63db\u5230\u76f4\u6392\u986f\u793a\u3002","zh-cn":"Double click to make text vertical.","ko-kr":"Double click to make text vertical."},TaketoriDefaultLang=document.getElementsByTagName("html")[0]&&document.getElementsByTagName("html")[0].lang?
document.getElementsByTagName("html")[0].lang.search(/tw/i)!=-1?"zh-tw":"ja-jp":"ja-jp",TaketoriTool=function(){};
TaketoriTool.prototype={element:function(a){arguments.length>1&&(a=Array.prototype.slice.call(arguments));this.elements=[];return this.appendElement(a)},list:function(){return this.elements?this.elements:[]},appendElement:function(a){arguments.length>1&&(a=Array.prototype.slice.call(arguments));if(!a)return this;if(!this.elements)this.elements=[];if(a.constructor==Array)for(var b=0,c=a.length;b<c;b++)this.appendElement(a[b]);else if(typeof a=="object")this.isIncluded(a)||(this.elements[this.elements.length]=
a);else if(typeof a=="string")if(a.match(/^(\w+)\.([\w\-]+)$/)){var d=RegExp.$1.toLowerCase(),f=RegExp.$2,g=[];if(typeof document.getElementsByClassName=="function"){g=document.getElementsByClassName(f);b=0;for(c=g.length;b<c;b++)g[b].tagName.toLowerCase()==d&&!this.isIncluded(g[b])&&(this.elements[this.elements.length]=g[b])}if(typeof document.getElementsByClassName!="function"||g.length==0){g=document.getElementsByTagName(d);d=RegExp("(^|\\s)"+f+"(?![\\w\\-])");b=0;for(c=g.length;b<c;b++)g[b].className.search(d)!=
-1&&!this.isIncluded(g[b])&&(this.elements[this.elements.length]=g[b])}}else(a=document.getElementById(a.replace("#","")))&&!this.isIncluded(a)&&(this.elements[this.elements.length]=a);return this},isIncluded:function(a){for(var b=0,c=this.elements.length;b<c;b++)if(this.elements[b]==a)return!0;return!1},removeClassName:function(a){return this.replaceClassName(a,"","ig")},replaceClassName:function(a,b,c){if(this.elements&&a!=null&&a!=""){a=RegExp("(^|\\s)"+a+"(?![\\w\\-])",c);b==null&&(b="");for(var c=
0,d=this.elements.length;c<d;c++)if(this.elements[c].className!=null)this.elements[c].className=this.elements[c].className.replace(a,b)}return this},addClassName:function(a){if(this.elements&&a!=null&&a!="")for(var b=RegExp("(^|\\s)"+a+"(?![\\w\\-])"),c=0,d=this.elements.length;c<d;c++)this.elements[c].className==null||this.elements[c].className==""?this.elements[c].className=a:this.elements[c].className.search(b)==-1&&(this.elements[c].className+=" "+a);return this},addEventListener:function(a,b,
c){c==null&&(c=!1);if(this.elements)for(var d=0,f=this.elements.length;d<f;d++)typeof this.elements[d].addEventListener=="function"?this.elements[d].addEventListener(a,b,c):typeof this.elements[d].attachEvent=="object"&&this.elements[d].attachEvent("on"+a,b);return b},removeEventListener:function(a,b,c){if(this.elements)for(var d=0,f=this.elements.length;d<f;d++)typeof this.elements[d].removeEventListener=="function"?this.elements[d].removeEventListener(a,b,c):this.elements[d].detachEvent&&this.elements[d].detachEvent("on"+
a,b)},stopPropagation:function(a){a.stopPropagation?a.stopPropagation():event.cancelBubble=!0},preventDefault:function(a){a.preventDefault?a.preventDefault():event.returnValue=!1}};var Taketori=function(){};
Taketori.prototype={isMSIE:navigator.appVersion.search(/MSIE/)!=-1?parseInt(navigator.appVersion.toLowerCase().replace(/.*msie[ ]/,"").match(/^[0-9]+/))==9?0:document.documentMode?document.documentMode:5:0,isIE9:navigator.appVersion.search(/MSIE/)!=-1&&parseInt(navigator.appVersion.toLowerCase().replace(/.*msie[ ]/,"").match(/^[0-9]+/))==9?!0:!1,isWritingModeReady:navigator.userAgent.search(/Android/)!=-1&&parseFloat(navigator.appVersion.toLowerCase().replace(/.*android[ ]/,"").match(/^[0-9]+(\.[0-9])/g))<
4.1?!1:navigator.appVersion.search(/MSIE/)!=-1&&parseInt(navigator.appVersion.toLowerCase().replace(/.*msie[ ]/,"").match(/^[0-9]+/))!=9||navigator.appVersion.search(/Trident/)!=-1&&parseInt(navigator.appVersion.toLowerCase().replace(/.*trident[\/]/,"").match(/^[0-9]+/))!=5||typeof document.createElement("div").style.MozWritingMode!="undefined"||typeof document.createElement("div").style.webkitWritingMode!="undefined"||typeof document.createElement("div").style.OWritingMode!="undefined"?!0:!1,isMultiColumnReady:typeof document.createElement("div").style.MozColumnWidth!=
"undefined"||typeof document.createElement("div").style.webkitColumnWidth!="undefined"||typeof document.createElement("div").style.webkitWritingMode!="undefined"&&typeof document.createElement("div").style.webkitColumnWidth!="undefined"||typeof document.createElement("div").style.OColumnWidth!="undefined"||typeof document.createElement("div").style.msColumnWidth!="undefined"||typeof document.createElement("div").style.columnWidth!="undefined"?!0:!1,isLegacy:navigator.appVersion.search(/MSIE/)!=-1||
typeof document.createElement("div").style.MozTransform!="undefined"||typeof document.createElement("div").style.webkitTransform!="undefined"||typeof document.createElement("div").style.OTransform!="undefined"||typeof document.createElement("div").style.transform!="undefined"?!1:!0,isTextEmphasisReady:typeof document.createElement("div").style.MozTextEmphasisStyle!="undefined"||typeof document.createElement("div").style.webkitTextEmphasisStyle!="undefined"||typeof document.createElement("div").style.OTextEmphasisStyle!=
"undefined"||typeof document.createElement("div").style.msTextEmphasisStyle!="undefined"||typeof document.createElement("div").style.textEmphasisStyle!="undefined"?!0:!1,document:new TaketoriTool,importCSS:function(){for(var a=!1,b=document.getElementsByTagName("link"),c=0,d=b.length;c<d;c++)b[c].href!=null&&b[c].href.search(/taketori\.css$/)!=-1&&(a=!0);if(a)return!0;if(this.config.cssPath==null||this.config.cssPath=="auto"){a=document.getElementsByTagName("script");c=0;for(d=a.length;c<d;c++)if(a[c].src.search(/taketori/)!=
-1){if(a[c].baseURI==null)this.config.cssPath=a[c].src.substring(0,a[c].src.lastIndexOf("/")).concat("/../css/");else if(a[c].baseURI.lastIndexOf("/")!=-1)this.config.cssPath=a[c].baseURI.substring(0,a[c].baseURI.lastIndexOf("/")).concat("/css/");break}}(c=document.getElementsByTagName("head")[0])?(d=document.createElement("link"),d.setAttribute("rel","stylesheet"),d.setAttribute("type","text/css"),d.setAttribute("href",this.config.cssPath+"taketori.css"),c.appendChild(d)):document.write('<link rel="stylesheet" type="text/css" href="'+
this.config.cssPath+'taketori.css" />')},setTemporaryCSS:function(a){if(!this.temporaryStyle)this.temporaryStyle=document.createElement("style"),this.temporaryStyle.setAttribute("type","text/css"),document.getElementsByTagName("head")[0].appendChild(this.temporaryStyle);this.temporaryStyle.appendChild(document.createTextNode(a))},removeTemporaryCSS:function(){if(this.temporaryStyle)document.getElementsByTagName("head")[0].removeChild(this.temporaryStyle),this.temporaryStyle=null},init:function(){if(!this.windowWidth){var a=
this;this.document.element(window).addEventListener("resize",function(){a.resizeTimer&&clearTimeout(a.resizeTimer);a.resizeTimer=setTimeout(function(){a.refresh()},500)})}if(!this.windowWidth)this.windowWidth=self.innerWidth?self.innerWidth:document.compatMode!=null&&document.compatMode!="BackCompat"?self.document.documentElement.clientWidth:self.document.body.clientWidth;if(!this.windowHeight)this.windowHeight=self.innerHeight?self.innerHeight:document.compatMode!=null&&document.compatMode!="BackCompat"?
self.document.documentElement.clientHeight:self.document.body.clientHeight;if(!this.isMSIE&&this.rubyDisabled==null)this.rubyDisabled=window.opera?!0:this.getStyle(document.createElement("ruby")).display=="block"?!0:!1},set:function(a){if(this.isLegacy)return this;if(!this.config)this.config={};a!=null&&this.merge(this.config,a);if(this.config.lang)this.config.lang=this.config.lang.toLowerCase();return this},merge:function(a,b){a||(a={});if(b!=null)for(var c in b)if(b[c]!=null)if(b[c].constructor==
Array)this.merge(a[c],b[c]);else if(typeof b[c]=="string"||typeof b[c]=="number"||typeof b[c]=="boolean")a[c]=b[c];return a},element:function(a){if(this.isLegacy)return this;arguments.length>1&&(a=Array.prototype.slice.call(arguments));if(!this.config.elements)this.config.elements=[];if(a&&a.constructor==Array)for(var b=0,c=a.length;b<c;b++)this.config.elements[this.config.elements.length]=a[b];else a&&(this.config.elements[this.config.elements.length]=a);return this},reset:function(a){this.config=
null;this.set(a)},japaneseReadableElements:function(a){for(var b=[],c=[],d=document.getElementsByTagName("p"),f=0,g=d.length;f<g;f++)c[c.length]=d[f];d=document.getElementsByTagName("br");f=0;for(g=d.length;f<g;f++)c[c.length]=d[f];f=0;for(g=c.length;f<g;f++)if(d=this.lookUpBlockElements(c[f],b),d!=null&&!this.isCountedElement(b,d)){var h=0;d.innerHTML.replace(/\u3002/g,function(){h++}).replace(/\u3001/g,function(){h+=0.5});b[b.length]={element:d,readabilityScore:h}}if(b.length>0){b=b.sort(function(a,
b){return b.readabilityScore-a.readabilityScore});c=[];f=0;for(g=b.length;f<g;f++)if(!this.isVerticalTextElement(b[f].element)&&(!a||a<b[f].readabilityScore))c[c.length]=b[f].element;return c}else return[document.body]},isVerticalTextElement:function(a){var b=this.getStyle(a);if(navigator.appVersion.search(/MSIE/)!=-1&&parseInt(navigator.appVersion.toLowerCase().replace(/.*msie[ ]/,"").match(/^[0-9]+/))==9&&typeof b.writingMode=="string"&&b.writingMode.toLowerCase()=="tb-rl")a.style.writingMode="lr-tb";
if(navigator.userAgent.search(/Android/)!=-1&&parseFloat(navigator.appVersion.toLowerCase().replace(/.*android[ ]/,"").match(/^[0-9]+(\.[0-9])/g))<4.1&&typeof b.webkitWritingMode=="string"&&b.webkitWritingMode.toLowerCase()=="vertical-rl")a.style.webkitWritingMode="horizontal-tb";return(navigator.userAgent.search(/Android/)!=-1&&parseFloat(navigator.appVersion.toLowerCase().replace(/.*android[ ]/,"").match(/^[0-9]+(\.[0-9])/g))<4.1?0:(navigator.appVersion.search(/MSIE/)!=-1&&parseInt(navigator.appVersion.toLowerCase().replace(/.*msie[ ]/,
"").match(/^[0-9]+/))!=9||navigator.appVersion.search(/Trident/)!=-1&&parseInt(navigator.appVersion.toLowerCase().replace(/.*trident[\/]/,"").match(/^[0-9]+/))!=5)&&typeof b.writingMode=="string"&&(b.writingMode.toLowerCase()=="tb-rl"||b.writingMode.toLowerCase()=="vertical-rl")||typeof b.MozWritingMode=="string"&&b.MozWritingMode.toLowerCase()=="vertical-rl"||typeof b.webkitWritingMode=="string"&&b.webkitWritingMode.toLowerCase()=="vertical-rl"||typeof b.OWritingMode=="string"&&b.OWritingMode.toLowerCase()==
"vertical-rl"||typeof b.writingMode=="string"&&b.writingMode.toLowerCase()=="vertical-rl")?!0:!1},isCountedElement:function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c].element==b)return!0;return!1},lookUpBlockElements:function(a){for(var b=null;a;){var c=a.tagName.toLowerCase();if(c=="div"||c=="td"||c=="th"||c=="dd"||c=="section"||c=="article"||c=="body"){if(a.taketori||!b)b=a;if(c=="body")break}a=a.parentNode}return b},isIncludedIn:function(a,b){if(a&&a.constructor==Array)for(var c=0,d=a.length;c<
d;c++)if(a[c]==b)return!0;return!1},escapeHTML:function(a){var b=document.createElement("div"),a=document.createTextNode(a);b.appendChild(a);return b.innerHTML},unescapeHTML:function(a){return a==null?"":a.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&amp;/g,"&")},getCookie:function(a){for(var b=[],c=document.cookie.split(/;\s*/),d=0,f=c.length;d<f;d++)if(c[d]!=""){var g=c[d].indexOf("=");if(g>=0){var h=c[d].substring(0,g),g=c[d].substring(g+1,c[d].length);b[h]=g}}return a!=
null&&b[a]!=null?b[a]:""},setCookie:function(a,b,c){if(!c)this.config.cookieExpires?c=this.config.cookieExpires:(c=new Date,c.setTime(c.getTime()+864E8));document.cookie=a+"="+b+"; expires="+c.toGMTString()+";"+(this.config.cookieDomain!=null&&this.config.cookieDomain!=""?" domain="+this.config.cookieDomain+";":"")+(this.config.cookiePath!=null&&this.config.cookiePath!=""?" path="+this.config.cookiePath:"")},deleteCookie:function(a){this.setCookie(a,"",new Date(70,0,1,0,0,1))},setOnLoad:function(a){if(this.isLegacy)return this;
typeof window.addEventListener=="function"?window.addEventListener("load",a,!1):typeof window.attachEvent=="object"&&window.attachEvent("onload",!this.isMultiColumnReady?function(){setTimeout(a,600)}:a);return this},getStyle:function(a){if(a.currentStyle)return a.currentStyle;else{var b=document.defaultView.getComputedStyle(a,null),c=document.createElement("div");if(b.length){for(var d=0,f=b.length;d<f;d++)c.style.setProperty(b[d],b.getPropertyValue(b[d]),"");d=0;for(f=a.style.length;d<f;d++)c.style.setProperty(a.style[d],
a.style.getPropertyValue(a.style[d]),"")}else c.style.cssText=b.cssText+a.style.cssText;return c.style}},counterClockwiseRotatedOuterHTML:function(a,b,c){var d,f=b.display!="inline"||b.cssFloat&&b.cssFloat!="none"||b.styleFloat&&b.styleFloat!="none"?!0:!1,g=!1,h=a.currentStyle;b||(b=this.getStyle(a));d=c?document.createElement("div"):a.cloneNode(!0);if(this.isWritingModeReady&&c)if(b.width&&b.width.search(/\d+\.?\d*(px|em)/i)!=-1&&parseInt(b.width)>0&&b.height&&b.height.search(/\d+\.?\d*(px|em)/i)!=
-1&&parseInt(b.height)>0)h||b.cssFloat&&b.cssFloat!="none"||b.display=="inline-block"?g=!0:(d.style.width="auto",d.style.height="auto");else if(b.width&&b.width.search(/\d+\.?\d*%/)!=-1||b.height&&b.height.search(/\d+\.?\d*%/)!=-1)d.style.width=b.height&&b.height.search(/\d+\.?\d*%/)!=-1?b.height:"auto",d.style.height=b.width&&b.width.search(/\d+\.?\d*%/)!=-1?b.width:"auto";else{if(b.width=="0px")d.style.width="auto";if(b.height=="0px")d.style.height="auto"}if(!this.isWritingModeReady||g||this.isWritingModeReady&&
!c){var i=0,j=0,k=!1;this.isWritingModeReady?(i=this.getMarginSize([b.paddingLeft,b.paddingRight,b.borderLeftWidth,b.borderRightWidth]),j=this.getMarginSize([b.paddingTop,b.paddingBottom,b.borderTopWidth,b.borderBottomWidth]),k=!0):(i=this.getMarginSize([b.paddingTop,b.paddingBottom,b.borderTopWidth,b.borderBottomWidth]),j=this.getMarginSize([b.paddingLeft,b.paddingRight,b.borderLeftWidth,b.borderRightWidth]));var m=!isNaN(parseInt(b.width))&&parseInt(b.width)>0?parseInt(b.width):a.width?a.width:
a.offsetWidth?a.offsetWidth-(k?i:j):null,l=!isNaN(parseInt(b.height))&&parseInt(b.height)>0?parseInt(b.height):a.height?a.height:a.offsetHeight?a.offsetHeight-(k?j:i):null,q=!1;if(!m||!l)this.makeClipboard(this.process.target,!0),this.clipboard.appendChild(d),m=d.offsetWidth?d.offsetWidth-(k?i:j):d.clientWidth,l=d.offsetHeight?d.offsetHeight-(k?j:i):d.clientHeight,this.clipboard.removeChild(d);if(!isNaN(m)&&!isNaN(l)){m+=i;l+=j;if(l>this.process.config.height)m=parseInt(m*this.process.config.height/
l),l=this.process.config.height,q=!0;if(m>this.process.config.width)l=parseInt(l*this.process.config.width/m),m=this.process.config.width,q=!0;if(q||g)if(i=m-i,j=l-j,g)h||b.display=="inline-block"?(d.width=j,d.style.width=j+"px"):d.style.width="auto",d.height=i,d.style.height=i+"px";else if(d.width=i,d.height=j,d.style.width=i+"px",d.style.height=j+"px",q&&f)d.style.overflow="auto"}}d.style.borderTopWidth=b.borderLeftWidth||0;d.style.borderRightWidth=b.borderTopWidth||0;d.style.borderBottomWidth=
b.borderRightWidth||0;d.style.borderLeftWidth=b.borderBottomWidth||0;d.style.borderTopColor=b.borderLeftColor||"";d.style.borderRightColor=b.borderTopColor||"";d.style.borderBottomColor=b.borderRightColor||"";d.style.borderLeftColor=b.borderBottomColor||"";d.style.borderTopStyle=b.borderLeftStyle||"none";d.style.borderRightStyle=b.borderTopStyle||"none";d.style.borderBottomStyle=b.borderRightStyle||"none";d.style.borderLeftStyle=b.borderBottomStyle||"none";if(f||!c||this.isWritingModeReady&&(!this.isMSIE||
this.isMSIE<8))d.style.paddingTop=b.paddingLeft||0,d.style.paddingRight=b.paddingTop||0,d.style.paddingBottom=b.paddingRight||0,d.style.paddingLeft=b.paddingBottom||0;if(this.isWritingModeReady){if(f&&c)d.style.overflowX=b.overflowY?b.overflowY:"visible",d.style.overflowY=b.overflowX?b.overflowX:"visible";if(b.backgroundPositionX||b.backgroundPositionY)d.style.backgroundPositionX=b.backgroundPositionY?b.backgroundPositionY=="top"?"left":b.backgroundPositionY=="bottom"?"right":b.backgroundPositionY:
"50%",d.style.backgroundPositionY=b.backgroundPositionX?b.backgroundPositionX=="left"?"top":b.backgroundPositionX=="right"?"bottom":b.backgroundPositionX:"50%";else if(b.backgroundPosition&&b.backgroundPosition.search(/(\S+)\s+(\S)/)!=-1)d.style.backgroundPosition=RegExp.$2+" "+RegExp.$1+";";if(f||!c||!this.isMSIE||this.isMSIE<8)d.style.marginTop=b.marginLeft||0,d.style.marginRight=b.marginTop||0,d.style.marginBottom=b.marginRight||0,d.style.marginLeft=b.marginBottom||0}else if(d.style.marginRight=
parseInt((b.marginRight&&b.marginRight!="auto"?parseInt(b.marginRight):0)+(l-m)/2)+"px",m-l>0?(d.style.marginTop=d.style.marginBottom="0px",d.style.marginLeft=parseInt((b.marginLeft&&b.marginLeft!="auto"?parseInt(b.marginLeft):0)+(l-m))+"px",d.style.paddingTop=parseInt(d.style.paddingTop)+(m-l)+"px"):(d.style.marginTop=parseInt((b.marginTop&&b.marginTop!="auto"?parseInt(b.marginTop):0)+(m-l)/2)+"px",d.style.marginBottom=parseInt((b.marginBottom&&b.marginBottom!="auto"?parseInt(b.marginBottom):0)+
(m-l)/2)+"px",d.style.marginLeft=parseInt((b.marginLeft&&b.marginLeft!="auto"?parseInt(b.marginLeft):0)+(l-m)/2)+"px"),b.backgroundPosition&&b.backgroundPosition.search(/(\S+)\s+(\S)/)!=-1)d.style.backgroundPosition=RegExp.$2+" "+RegExp.$1+";";return c?d.style.cssText+";"+a.style.cssText:this.outerHTML(d)},outerHTML:function(a){if(!a)return"";var b=document.createElement("div");b.appendChild(a.cloneNode(!0));return b.innerHTML},rotatedBlockAdditionalCSSText:function(a,b,c,d){c==null&&(c=0);if(this.isWritingModeReady)return"width:"+
b+"px;height:"+a+"px;"+(c?(!d?"padding-bottom:":"margin-bottom:")+c+"px;":"")+(!d?"position:relative;overflow:auto;overflow-x:auto;overflow-y:hidden;":"");else{var f=this.isIE9?"overflow-x:hidden;overflow-y:hidden;":"overflow-x:visible;overflow-y:visible;";return"width:"+a+"px;height:"+b+"px;margin-top:-"+b+"px;margin-right:"+(b-a-c)+"px;margin-bottom:"+(a+c)+"px;margin-left:0;"+(!d?"padding-right:"+c+"px;overflow:auto;"+f:"")}},toVertical:function(a){if(this.isLegacy)return this;var b=this;if(a==
null||a)this.setOnLoad(function(){b.toVertical(!1)});else{this.importCSS();var c=!1,d=!1;if(!this.targetElements)if(!this.config.elements||this.config.elements[0]=="=auto")this.targetElements=this.japaneseReadableElements(this.config.minScore==null?3:this.config.minScore),this.config.togglable=!1,c=!0;else if(this.config.elements[0]=="=dblclick")d=c=!0;else{var f=this.document.element(this.config.elements).list();this.targetElements=[];for(var a=0,g=f.length;a<g;a++)this.isVerticalTextElement(f[a])||
(this.targetElements[this.targetElements.length]=f[a])}if(c){if(!this.toggleEventAttached)this.document.element(document.body).addEventListener("dblclick",function(a){b.toggle(b.lookUpBlockElements(a.target||event.target||event.srcElement));b.document.stopPropagation(a);b.document.preventDefault(a)}),this.toggleEventAttached=!0;if(d)return a=navigator.browserLanguage||navigator.language||navigator.userLanguage,a=a.search(/tw/i)!=-1?"zh-tw":a.search(/(zh|cn)/i)!=-1?"zh-cn":a.search(/(ko|kr)/i)!=-1?
"ko-kr":"ja-jp",alert(TaketoriDblClickAlert[a]),this}if(this.ttbDisabled==null)this.ttbDisabled=this.getCookie("TTB_DISABLED")=="true"?!0:!1;if(this.config.togglable){if(!this.config.cookieDomain)this.config.cookieDomain=document.domain;if(!this.config.cookiePath)this.config.cookiePath="/";a=0;for(g=this.targetElements.length;a<g;a++){c=this.targetElements[a];if(!c.taketori)c.taketori={};if(!c.taketori.toggleEventAttached)this.document.element(c).addEventListener("dblclick",function(a){b.document.stopPropagation(a);
b.document.preventDefault(a);b.ttbDisabled?(b.deleteCookie("TTB_DISABLED"),b.ttbDisabled=!1):(b.setCookie("TTB_DISABLED","true"),b.ttbDisabled=!0);b.toVertical(!1)}),c.taketori.toggleEventAttached=!0;this.toggle(c,this.ttbDisabled,!0)}}else if(!this.ttbDisabled){a=0;for(g=this.targetElements.length;a<g;a++)this.make(this.targetElements[a])}}return this},configClone:function(a){if(!a)return{};for(var b={},c=["width","height","fontFamily","maxHeight","multiColumnEnabled","gap","contentWidth","contentHeight",
"onbreak","classNameImported","lang"],d=0,f=c.length;d<f;d++)a[c[d]]!=null&&(b[c[d]]=a[c[d]]);return b},toggleAll:function(){if(this.isLegacy)return this;if(!this.config.cookieDomain)this.config.cookieDomain=document.domain;if(!this.config.cookiePath)this.config.cookiePath="/";this.ttbDisabled?(this.deleteCookie("TTB_DISABLED"),this.ttbDisabled=!1):(this.setCookie("TTB_DISABLED","true"),this.ttbDisabled=!0);for(var a=0,b=this.targetElements.length;a<b;a++)this.toggle(this.targetElements[a],this.ttbDisabled,
!0);return this},clearAll:function(){if(this.isLegacy)return this;if(!this.config.cookieDomain)this.config.cookieDomain=document.domain;if(!this.config.cookiePath)this.config.cookiePath="/";if(!this.ttbDisabled)this.setCookie("TTB_DISABLED","true"),this.ttbDisabled=!0;for(var a=0,b=this.targetElements.length;a<b;a++)this.toggle(this.targetElements[a],!0,!0,!0);return this},appendTarget:function(a){if(!this.isVerticalTextElement(a))this.targetElements?this.isIncludedIn(this.targetElements,a)||(this.targetElements[this.targetElements.length]=
a):this.targetElements=Array(a)},removeTarget:function(a){if(this.targetElements){for(var b=[],c=0,d=this.targetElements.length;c<d;c++)this.targetElements[c]!=a&&(b[b.length]=this.targetElements[c]);this.targetElements=b}},makeClipboard:function(a,b){if(b||this.process.isBreakable)if(this.clipboard&&this.clipboard.parentNode!=a&&this.removeClipboard(),!this.clipboard){this.clipboard=document.createElement("div");this.clipboard.style.position="absolute";a.appendChild(this.clipboard);var c=this.windowWidth>
this.windowHeight?this.windowWidth:this.windowHeight;this.clipboard.style.top="-"+(c+100)+"px";this.clipboard.style.left="-"+(c+100)+"px";this.clipboard.style.width=c+"px";this.clipboard.style.height=c+"px";this.clipboard.style.overflow="auto"}},removeClipboard:function(){this.temporaryContent&&this.temporaryContent.parentNode.removeChild(this.temporaryContent);this.clipboard&&this.clipboard.parentNode.removeChild(this.clipboard);this.temporaryContent=this.clipboard=null},toPx:function(a,b,c,d){return!a?
0:c?a.search(/(\d+\.\d+)/)!=-1?parseInt(RegExp.$1*b):parseInt(1.5*b):a.search(/\d+\.?\d*em/i)!=-1?parseInt(parseFloat(a)*b):a.search(/\d+\.?\d*%/)!=-1?parseInt(parseFloat(a)*(d?d:b)/100):a.search(/\d/)!=-1?parseInt(a):a},getFontSize:function(a){if(!isNaN(a)||a.search(/\d+px/)!=-1)return parseInt(a);else{var b=this.getStyle(document.body).fontSize,b=b.search(/\d+\.?\d*(em|%)/)!=-1?this.toPx(b,16):parseInt(b),a=this.toPx(a,b);return a>0?a:16}},getHeight:function(a){return!isNaN(a)||a.search(/\d+px/)!=
-1?parseInt(a):null},setCurrentConfig:function(a,b){b||(b=this.configClone(this.config));if(!b.classNameImported){var c=a.className;if(c)for(var d=["width","height","fontFamily","maxHeight","multiColumnEnabled","gap","contentWidth","contentHeight","lang"],f=0,g=d.length;f<g;f++)if(c.search(RegExp("(^|\\s)taketori-"+d[f]+"-([\\w\\.\\-\\%]+)(?![\\w\\-])","i"))!=-1)b[d[f]]=RegExp.$2;b.classNameImported=!0}b.lang=b.lang?b.lang.toLowerCase():TaketoriDefaultLang;this.init();c=this.getStyle(a);d=this.getFontSize(c.fontSize);
this.process={target:a,done:!1,isMultiColumnEnabled:!1,noCJK:0,latin:0,width:0,columnCount:0,letterSpacing:"",textIndent:"",textIndentPTag:"",pTagStart:!1,pointer:"",fontSize:"",openTagsHTML:"",listStart:[],listStyleType:[],currentStyle:{},openTags:[],closeTags:[],columnHTML:"",content:"",config:{}};if(typeof b.multiColumnEnabled=="boolean"&&b.multiColumnEnabled||this.isMultiColumnReady&&b.multiColumnEnabled&&b.multiColumnEnabled=="auto")this.process.config.multiColumnEnabled=!0;if(this.isMultiColumnReady&&
this.process.config.multiColumnEnabled)this.process.isMultiColumnEnabled=!0;if(!this.isMultiColumnReady&&this.process.config.multiColumnEnabled||b.contentHeight&&b.contentWidth)this.process.isBreakable=!0;f=this.getElementWidth(a,c);if(b.contentWidth)this.process.config.contentWidth=this.toPx(b.contentWidth,d,!1,f);if(b.contentHeight)this.process.config.contentHeight=this.toPx(b.contentHeight,d,!1,f);this.process.config.width=b.width?this.toPx(b.width,d,!1,f):this.process.config.contentWidth!=null?
this.process.config.contentWidth:f;this.process.config.gap=b.gap!=null?this.toPx(b.gap,d):d*2;if(b.height==null)if(f=this.getHeight(c.height),f!=null)this.process.config.height=f;else{if(!b.maxHeight)b.maxHeight="36em";f=this.toPx(b.maxHeight,d);d=this.process.config.contentHeight?this.process.config.contentHeight:this.windowHeight;if(this.process.config.multiColumnEnabled){if(f=Math.ceil(d/(f+this.process.config.gap)),this.process.config.height=parseInt((d-40)/f)-this.process.config.gap,this.process.config.contentHeight)this.process.config.columnCount=
f}else d=d-this.process.config.gap-18,this.process.config.height=d>f?f:d}else this.process.config.contentHeight&&this.process.config.multiColumnEnabled?(d=this.toPx(b.height,d),this.process.config.columnCount=Math.ceil(this.process.config.contentHeight/(d+this.process.config.gap)),this.process.config.height=parseInt((this.process.config.contentHeight+this.process.config.gap)/this.process.config.columnCount)-this.process.config.gap):this.process.config.height=b.height&&b.height=="width"?this.process.config.width:
this.process.config.multiColumnEnabled?this.toPx(b.height,d):this.process.config.contentHeight||this.toPx(b.height,d);if(c.letterSpacing!="normal")this.process.letterSpacing=c.letterSpacing;if(c.textIndent!="0px")this.process.textIndent=this.process.textIndentPTag=c.textIndent,a.style.textIndent="0px";this.process.pointer=c.cursor;this.process.fontSize=c.fontSize;this.process.currentConfig=b;return this},getElementWidth:function(a,b){return a.offsetWidth||a.scrollWidth?(a.offsetWidth?a.offsetWidth:
a.scrollWidth)-this.getMarginSize([b.paddingLeft,b.paddingRight,b.borderLeftWidth,b.borderRightWidth]):parseInt(b.width.replace(/\D+/,""))-this.getMarginSize([b.paddingLeft,b.paddingRight,b.borderLeftWidth,b.borderRightWidth])},getMarginSize:function(a){for(var b=0,c=0,d=a.length;c<d;c++)a[c]&&!isNaN(parseInt(a[c]))&&(b+=parseInt(a[c]));return b},getWidth:function(a){this.setTaketoriClassName(this.clipboard);if(!this.temporaryContent)this.temporaryContent=document.createElement("div"),this.setTemporaryContentStyle(),
this.clipboard.appendChild(this.temporaryContent);this.temporaryContent.innerHTML=a;this.process.width=this.getTemporaryContentWidth();this.clipboard.className="";return this.process.width},setTemporaryContentStyle:function(){this.temporaryContent.className="taketori-col";this.isWritingModeReady?(this.temporaryContent.style.height=this.process.config.height+"px",this.temporaryContent.style.width="16px"):(this.temporaryContent.style.overflow="auto",this.temporaryContent.style.width=this.process.config.height+
"px")},getTemporaryContentWidth:function(){return this.isWritingModeReady?this.temporaryContent.scrollWidth||this.temporaryContent.clientWidth||this.temporaryContent.offsetWidth:this.temporaryContent.scrollHeight||this.temporaryContent.clientHeight||this.temporaryContent.offsetHeight},hasToBreak:function(a){if(!this.temporaryContent)this.temporaryContent=document.createElement("div"),this.clipboard.appendChild(this.temporaryContent);var b=0,b=!1;this.temporaryContent.className="taketori-col";this.temporaryContent.style.overflow=
"auto";this.setTaketoriClassName(this.clipboard);if(this.process.config.columnCount&&this.process.config.columnCount>1){var c=this.process.config.width*this.process.config.columnCount;if(this.process.width+50<c)this.setTemporaryContentStyle(),this.temporaryContent.innerHTML=a,this.process.width=this.getTemporaryContentWidth();this.process.width+50>=c&&(b=this.getMultiColumnWidth(a),b=b>this.process.config.contentHeight?!0:!1)}else this.isWritingModeReady?(this.temporaryContent.style.height=this.process.config.contentHeight+
"px",this.temporaryContent.innerHTML=a,this.process.width=this.temporaryContent.scrollWidth||this.temporaryContent.clientWidth||this.temporaryContent.offsetWidth):(this.temporaryContent.style.width=this.process.config.contentHeight+"px",this.temporaryContent.innerHTML=a,this.process.width=this.temporaryContent.scrollHeight||this.temporaryContent.clientHeight||this.temporaryContent.offsetHeight),b=this.process.width>this.process.config.contentWidth?!0:!1;this.clipboard.className="";return b},getMultiColumnWidth:function(a){if(!this.temporaryContent)this.temporaryContent=
document.createElement("div"),this.clipboard.appendChild(this.temporaryContent);var b=0;this.setTaketoriClassName(this.clipboard);this.setMultiColumnStyle(this.temporaryContent);this.temporaryContent.innerHTML=a;b=this.isWritingModeReady?this.getTotalHeight(this.temporaryContent):this.getTotalWidth(this.temporaryContent);this.clipboard.className="";return b},setMultiColumnStyle:function(a){a.className="taketori-col taketori-multi-column";a.style.overflow="auto";this.isWritingModeReady?(a.style.width=
this.process.config.width+"px",a.style.height=this.process.config.height+"px"):(a.style.width=this.process.config.height+"px",a.style.height=this.process.config.width+"px");a.style.MozColumnWidth=this.process.config.height+"px";a.style.webkitColumnWidth=this.process.config.height+"px";a.style.OColumnWidth=this.process.config.height+"px";a.style.columnWidth=this.process.config.height+"px";a.style.MozColumnGap=this.process.config.gap+"px";a.style.webkitColumnGap=this.process.config.gap+"px";a.style.OColumnGap=
this.process.config.gap+"px";a.style.columnGap=this.process.config.gap+"px"},setMultiColumnWidth:function(a){if(this.isWritingModeReady){var b=this.getTotalHeight(a);a.style.height=b+"px";a.style.overflow="visible";this.fixMargin(a,this.process.config.width,b)}else b=this.getTotalWidth(a),a.style.width=b+"px",a.style.overflow="visible",this.fixMargin(a,b,this.process.config.width)},getTotalWidth:function(a){return Math.ceil((a.scrollWidth||a.clientWidth||a.offsetWidth)/(this.process.config.height+
this.process.config.gap))*(this.process.config.height+this.process.config.gap)-this.process.config.gap},getTotalHeight:function(a){return Math.ceil((a.scrollHeight||a.clientHeight||a.offsetHeight)/(this.process.config.height+this.process.config.gap))*(this.process.config.height+this.process.config.gap)-this.process.config.gap},setTaketoriClassName:function(a){var b=this.isWritingModeReady?"taketori-writingmode-ttb":"taketori-ttb";b+=this.isIE9?" taketori-ttb-hidden":" taketori-ttb-visible";this.rubyDisabled&&
(b+=" taketori-ruby-disabled");this.isTextEmphasisReady||(b+=" taketori-text-emphasis-disabled");this.isWritingModeReady&&navigator.userAgent.search(/WebKit/i)!=-1&&navigator.userAgent.search(/Windows/i)!=-1&&(b+=" taketori-atsign-"+this.process.currentConfig.lang);b+=" taketori-lang-"+this.process.currentConfig.lang;a.className+=(a.className?" ":"")+b},removeTaketoriClassName:function(a){this.document.element(a).removeClassName("taketori-ttb").removeClassName("taketori-ttb-hidden").removeClassName("taketori-ttb-visible").removeClassName("taketori-writingmode-ttb").removeClassName("taketori-ruby-disabled").removeClassName("taketori-(lang|serif|sans-serif|cursive|kai)[\\w\\-]*")},
make:function(a,b){this.document.element(a).addClassName("taketori-in-progress");var c=this;setTimeout(function(){b||c.setCurrentConfig(a);c.makeClipboard(a);c.parse(a,!0);c.complement(a);c.removeClipboard();c.document.element(a).removeClassName("taketori-in-progress")},120)},isSkipClass:function(a){if(this.config.skipClass&&a.className)for(var a=0,b=this.config.skipClass.length;a<b;a++)if(this.elements.className.search(RegExp("(^|\\s)"+this.config.skipClass[a]+"(?![\\w\\-])"))!=-1)return!0;return!1},
isSkipId:function(a){return this.config.skipId&&a.id&&this.isIncludedIn(this.config.skipId,thisNode.id)?!0:!1},findChildNode:function(a){for(var a=a.childNodes,b=0,c=a.length;b<c;b++)if(a[b].nodeType=="1")return a[b];return null},parse:function(a,b){if(a!=this.clipboard){a.taketori&&a.taketori.ttb&&this.toggle(a,!0,!0);var c=a.nodeName.toLowerCase(),d="",f="",g="",h="",i="",j="",j=!1,k=a.nodeType,m=null,l=!1,q=a.hasChildNodes&&a.hasChildNodes(),o=pRight=pTop=pBottom="",r=mRight=mTop=mBottom="";switch(k){case 1:k=
this.getStyle(a);if(this.process.isBreakable){var p=this.getFontSize(k.fontSize);this.process.lineHeight=this.toPx(k.lineHeight,p,!0);if(!this.process.lineLength)this.process.lineLength=this.process.config.height;if(!b&&k.display=="block"){var v=this.process.lineLength;this.process.lineLength-=this.getMarginSize([k.marginTop,k.marginBottom,k.paddingTop,k.paddingBottom,k.borderTopWidth,k.borderBottomWidth]);if(this.process.lineLength<p)this.process.lineLength=p}this.process.roughFormula=p*this.process.lineHeight/
this.process.lineLength}if(!b){if(this.isIncludedIn(["img","iframe","object","embed","video","audio","textarea"],c)){this.appendHTML(this.counterClockwiseRotatedOuterHTML(a,k));break}else if(this.isSkipClass(a)||this.isSkipId(a)){this.appendHTML(this.counterClockwiseRotatedOuterHTML(a,k));break}else if(this.isIncludedIn(["link","meta","base","script","style","map"],c)){this.process.columnHTML+=this.outerHTML(a);break}else if(c=="!")break;else if(this.isIncludedIn(["br","input","select","option"],
c)||this.isMSIE&&this.isMSIE<8&&c=="table"){this.appendHTML(this.outerHTML(a));break}for(var x=a.attributes,z=!1,H=!1,A=0,p=x.length;A<p;A++){var s=x[A],I=s.nodeName.toLowerCase(),u=typeof s.nodeValue=="string"||typeof s.nodeValue=="number"?this.escapeHTML(s.nodeValue):I=="style"&&a.style.cssText!=null?a.style.cssText.replace(/[\w\-]+:/g,function(a){return a.toLowerCase()}):I=="class"&&a.className!=null?a.className:null;if(s.specified&&u&&!this.isIncludedIn(this.stripAttributes,I)){switch(I){case "style":h=
u;u="";break;case "class":i+=(i?" ":"")+u;k&&k.cursor=="pointer"&&(i+=(i?" ":"")+"cursorPointer");if(u.search(/(^|\s)ltr(?![\w\-])/)!=-1)this.process.ltr||(z=!0),this.process.ltr=!0;u="";break;case "dir":if(u.search(/(^|\s)ltr(?![\w\-])/)!=-1)this.process.ltr||(z=!0),this.process.ltr=!0;i+=(i?" ":"")+u;break;case "id":o=document.getElementById(u);(s=o.currentStyle)?window.opera?(o=s.paddingLeft,pRight=s.paddingRight,pTop=s.paddingTop,pBottom=s.paddingBottom,r=s.marginLeft,mRight=s.marginRight,mTop=
s.marginTop,mBottom=s.marginBottom):(o=s["padding-left"],pRight=s["padding-right"],pTop=s["padding-top"],pBottom=s["padding-bottom"],r=s["margin-left"],mRight=s["margin-right"],mTop=s["margin-top"],mBottom=s["margin-bottom"]):(s=document.defaultView.getComputedStyle(o,null),k.textDecoration=s.getPropertyValue("text-decoration"),o=s.getPropertyValue("padding-left"),pRight=s.getPropertyValue("padding-right"),pTop=s.getPropertyValue("padding-top"),pBottom=s.getPropertyValue("padding-bottom"),r=s.getPropertyValue("margin-left"),
mRight=s.getPropertyValue("margin-right"),mTop=s.getPropertyValue("margin-top"),mBottom=s.getPropertyValue("margin-bottom"));if(k.letterSpacing!="normal")this.process.letterSpacing=k.letterSpacing;if(k.textIndent!="0px")this.process.textIndent=this.process.textIndentPTag=k.textIndent}u!=null&&u!=""&&(g+=" "+I+'="'+u+'"')}}if(c=="p")this.process.pTagStart=!0;z?h+=this.counterClockwiseRotatedOuterHTML(a,k,!0):this.isWritingModeReady&&!this.isIncludedIn(["table","caption","thead","tbody","tr","td","th",
"tfoot"],c)&&(h+=this.counterClockwiseRotatedOuterHTML(a,k,!0));if(!this.process.ltr&&(!this.isMSIE||this.isMSIE>7)){c=="li"&&this.process.listStyleType&&this.process.listStyleType[this.process.listStyleType.length-1]!=""&&(g+=' data-marker="'+this.getListMarkerText()+'"');if(c=="ul"||c=="ol")j=!0,this.process.listStart[this.process.listStart.length]=0,p=k.listStyleType.toLowerCase(),this.isIncludedIn(["none","disc","circle","square"],p)?this.process.listStyleType[this.process.listStyleType.length]=
"":(this.process.listStyleType[this.process.listStyleType.length]=p,i+=(i?" ":"")+"cjk");if(this.isWritingModeReady&&c=="strong"){if(!this.isTextEmphasisReady)this.process.kenten||(H=!0),this.process.kenten=!0;i+=(i?" ":"")+"bo-ten"}!this.isWritingModeReady&&k.fontStyle&&k.fontStyle.toLowerCase()=="italic"&&q&&(i+=(i?" ":"")+"italic");if(k.textDecoration&&q&&(p=k.textDecoration.toLowerCase(),p!="none"&&(p.search(/underline/i)!=-1&&p.search(/overline/i)!=-1?(i+=(i?" ":"")+"border-bothline",m=this.lineMarginHeight(k)):
p.search(/underline/i)!=-1?(i+=(i?" ":"")+"underline border-underline",m=this.lineMarginHeight(k)):p.search(/overline/i)!=-1&&(i+=(i?" ":"")+"overline border-overline",m=this.lineMarginHeight(k)),!this.isWritingModeReady&&m)))this.process.lineMarginHeight||(l=!0),this.process.lineMarginHeight=m}m="";if(i){x=0;for(p=this.targetElements.length;x<p;x++)if(a.id==this.targetElements[x].id){this.removeTarget(this.targetElements[x]);i=i.replace("taketori-in-progress","");k&&k.height&&k.width&&(m="width:"+
k.height+";height:"+k.width+";");break}g+=c=="span"?' class="'+i+' verticalMiddle"':' class="'+i+'"'}else c=="span"&&(g+=' class="verticalMiddle"');h&&(g+=' style="'+h+'"');h=tmpChildNode=i=tmpNodeName="";if(a.id){h=this.findChildNode(a);if(h!=null)i=h.id;if(i!=""){p=tmpWidth=i=tmpName="";h=this.findChildNode(h);if(h!=null)i=h.id;i!=""&&(tmpChildNode=h,tmpName=tmpChildNode.nodeName.toLowerCase());if(i!=""&&tmpName=="img"||tmpName=="iframe")tmpName=="img"?(p=tmpChildNode.height,tmpWidth=tmpChildNode.width):
(p=tmpChildNode.clientHeight,tmpWidth=tmpChildNode.clientWidth),p&&p!=""&&tmpWidth&&tmpWidth!=""&&(g=g.search('style="')!=-1?g.slice(0,-1)+"width:"+p+"px;height:"+tmpWidth+'px;"':g+' style="width:'+p+"px;height:"+tmpWidth+'px;"')}}i=tmpChildNode=i=childNodeId="";h=this.findChildNode(a);if(h!=null)childNodeId=h.id;if(childNodeId!=""){tmpChildNode=h;tmpNodeName=tmpChildNode.nodeName.toLowerCase();if(tmpNodeName=="img")i=tmpChildNode.height;if(tmpNodeName=="iframe")i=tmpChildNode.clientHeight}i!=""&&
(g=g.search('style="')!=-1?g.slice(0,-1)+"width:"+i+'px;"':g+' style="width:'+i+'px;"');if(a.childNodes.length==0||a.childNodes.length==1&&a.childNodes[0].nodeType==8)k&&k.height&&k.width&&(g=g.search('style="')!=-1?g.slice(0,-1)+"width:"+k.height+"; height:"+k.width+';"':g+' style="width:'+k.height+"; height:"+k.width+';"');m&&(g=g.search('style="')!=-1?g.slice(0,-1)+m+'"':g+' style="'+m+'"');k.textIndent!="0px"&&(g.search('style="')!=-1?g=g.slice(0,-1)+'text-indent:0px;"':g+=' style="text-indent:0px;"');
b||(d+="<"+c+g)}if(q){if(!b){f=marginStr="";o==""&&pRight==""&&pTop==""&&pBottom==""||o=="0px"&&pRight=="0px"&&pTop=="0px"&&pBottom=="0px"||(f="padding:"+pRight+" "+pBottom+" "+o+" "+pTop+";");r==""&&mRight==""&&mTop==""&&mBottom==""||r=="0px"&&mRight=="0px"&&mTop=="0px"&&mBottom=="0px"||(marginStr="margin:"+mRight+" "+mBottom+" "+r+" "+mTop+";");if(f!=""||marginStr!="")d=d.search('style="')!=-1?d.slice(0,-1)+f+marginStr+'"':d+'style="'+f+marginStr+'"';this.process.columnHTML+=d+">";j&&(d+=' start=""');
d+=">";f="</"+c+">";this.process.openTags[this.process.openTags.length]=d;this.process.closeTags[this.process.closeTags.length]=c}if(b&&c!="div"&&(!document.getElementById(a.id).style.paddingTop||document.getElementById(a.id).style.paddingTop=="0px"))document.getElementById(a.id).style.paddingTop="1px";A=0;for(p=a.childNodes.length;A<p;A++)this.parse(a.childNodes[A]);if(!b){this.process.columnHTML+=f;this.process.openTags.pop();this.process.closeTags.pop();if(z)this.process.ltr=null;if(H)this.process.kenten=
null;if(l)this.process.lineMarginHeight=null;j&&(this.process.listStart.pop(),this.process.listStyleType.pop())}}else b||(d+="></"+c+">",this.process.columnHTML+=d);if(v)this.process.lineLength=v;break;case 3:var j=this.escapeHTML(a.nodeValue),j=j.replace(/\uFF0F\uFF3C/g,"\u3033\u3035").replace(/\uFF3C\uFF0F/g,"\u3033\u3035").replace(/\uFF0F\u0022\uFF3C/g,"\u3034\u3035").replace(/\uFF3C\u0022\uFF0F/g,"\u3034\u3035"),n=this,C=0;j.replace(/&#?\w+;|\s+|./g,function(a){if(a.search(/^[\u1100-\u11FF\u2014\u2025-\u2026\u2030-\u20AB\u20AD-\u218F\u2460-\u24FF\u2500-\u254B\u2600-\u261F\u2620-\u277F\u2E80-\u2FDF\u2FF0-\u4DBF\u4E00-\u9FFF\uA960-\uA97F\uAC00-\uD7AF\uD7B0-\uD7FF\uF900-\uFAFF\uFE30-\uFE4F\uFF00\uFF01\uFF03-\uFF06\uFF08-\uFF0C\uFF0E-\uFF1B\uFF1F-\uFF3D\uFF40-\uFF5B\uFF5D-\uFF60\uFFA0-\uFFEF]$/)!=
-1){n.setCJK();if((!n.isWritingModeReady||n.process.kenten)&&!n.process.ltr){var b=n.process.pointer=="pointer"?" cursorPointer":"",b="<span"+(!n.process.ltr?' class="'+n.getCJKClassName(a)+b+'"':""),c=underMBottom=letterMTop=letterSpacing=textIndent="";if(!n.process.ltr&&n.process.lineMarginHeight||n.process.letterSpacing||n.process.textIndent!=""&&n.process.textIndent!="0px"){if(!n.process.ltr&&n.process.lineMarginHeight)c=n.process.lineMarginHeight,underMBottom="margin-bottom:"+n.process.lineMarginHeight+
"px;",letterMTop!=""&&(c=eval(c+parseInt(letterMTop)),letterMTop=letterSpacing="");var d=n.getCJKClassName(a);if(n.process.letterSpacing&&d.indexOf("cjk")!=-1&&n.process.letterSpacing!="0px")if(d=="cjk")d=n.process.letterSpacing,letterMTop=d.indexOf("-")!=-1?d.replace(/[^.0-9]/g,""):"-"+parseInt(d),c!=""?(d=eval(c+parseInt(letterMTop)),underMBottom="margin-top:"+d+"px;"+underMBottom,c=""):letterSpacing="margin-top:"+letterMTop+"px;";else if(d.indexOf("cho-on")!=-1||d.indexOf("tou-ten")!=-1||d.indexOf("ku-ten")!=
-1||d.indexOf("kogaki")!=-1){var f=n.process.letterSpacing.replace(/[^-.0-9]/g,""),g="",g=d.indexOf("tou-ten")!=-1?eval(Number(f)+parseInt(n.process.fontSize)*0.64):d.indexOf("ku-ten")!=-1?eval(Number(f)+parseInt(n.process.fontSize)*0.64):d.indexOf("kogaki")!=-1?eval(Number(f)/2+parseInt(n.process.fontSize)*0.15):d.indexOf("cho-on")!=-1?eval(Number(f)/2):eval(Numberp(f)+parseInt(n.process.fontSize)),g=Math.round(g*100/100),g=d.indexOf("cho-on")!=-1?"padding-right:"+g+"px;padding-left:"+g+"px;":d.indexOf("kogaki")!=
-1?"margin-right:"+g+"px!important;margin-left:"+g+"px!important;":"margin-right:"+g+"px!important;";c!=""?(letterSpacing="margin-top:"+c+"px;"+underMBottom+"letter-spacing:0px;"+g,c=underMBottom=""):letterSpacing="letter-spacing:0px;"+g}if(n.process.textIndent!=""&&n.process.textIndent!="0px")textIndent="margin-left:"+n.process.textIndent+";",n.process.textIndent="0px",n.process.pTagStart=!1}if(underMBottom!=""||letterSpacing!=""||textIndent!="")b+=' style="'+(c!=""?"margin-top:"+c+"px;":"")+underMBottom+
letterSpacing+textIndent+'"';if(textIndent==""&&n.process.textIndentPTag!=""&&n.process.textIndentPTag!="0px"&&n.process.pTagStart)b.search('style="')!=-1?b=b.slice(0,-1)+"margin-left:"+n.process.textIndentPTag+';"':b+=' style="margin-left:'+n.process.textIndentPTag+';"',n.process.pTagStart=!1;b+=">"+a+"</span>";a=n.kinsokuShori(b)}C++}else if(a.search(/^\s+$/)!=-1)C>0&&(C+=0.5);else{a.search(/^[0-9a-zA-Z]$/)!=-1?(C+=0.5,n.process.latin++):(C++,n.process.latin=0);if(n.process.noCJK==0){b=n.process.pointer==
"pointer"?" cursorPointer":"";b='<span class="nocjk notcy'+b+'"';if(n.process.textIndent!=""&&n.process.textIndent!="0px")b+=' style="margin-left:'+n.process.textIndent+';"',n.process.textIndent="0px",n.process.pTagStart=!1;if(n.process.textIndentPTag!=""&&n.process.textIndentPTag!="0px"&&n.process.pTagStart)b+=' style="margin-left:'+n.process.textIndentPTag+';"',n.process.pTagStart=!1;b+=">"+a;a=b}this.isTextEmphasisReady||n.process.noCJK++}!n.process.isBreakable||C>1&&n.isNoBreak(n.process.width+
C*n.process.roughFormula+n.process.lineHeight)?n.process.columnHTML+=a:(C=1,n.appendHTML(a))});this.setCJK()}}},isNoBreak:function(a){return this.isWritingModeReady||!this.process.isMultiColumnEnabled?a<this.process.config.width?!0:!1:this.process.config.contentHeight&&this.process.config.contentWidth?this.process.config.columnCount&&this.process.config.columnCount>1?a+50<this.process.config.width*this.process.config.columnCount?!0:!1:a<this.process.config.contentHeight?!0:!1:!0},setCJK:function(){if(this.process.noCJK>
0)this.process.columnHTML=this.process.columnHTML.replace('<span class="nocjk notcy','<span class="nocjk')+"</span>";this.process.latin=this.process.noCJK=0},lineMarginHeight:function(a){var b=a.lineHeight,a=this.getFontSize(a.fontSize);return b.search(/\d+px/)!=-1?parseInt((parseInt(b)-a)/2):parseInt((parseFloat(b)*a-a)/2)},getListMarkerText:function(){var a=++this.process.listStart[this.process.listStart.length-1],b=this.process.listStyleType[this.process.listStyleType.length-1];return b=="A"||
b=="\u30a2"||b=="upper-latin"||b=="katakana"?(b=["\u30a2","\u30a2","\u30a4","\u30a6","\u30a8","\u30aa","\u30ab","\u30ad","\u30af","\u30b1","\u30b3","\u30b5","\u30b7","\u30b9","\u30bb","\u30bd","\u30bf","\u30c1","\u30c4","\u30c6","\u30c8","\u30ca","\u30cb","\u30cc","\u30cd","\u30ce","\u30cf","\u30d2","\u30d5","\u30d8","\u30db","\u30de","\u30df","\u30e0","\u30e1","\u30e2","\u30e4","\u30e6","\u30e8","\u30e9","\u30ea","\u30eb","\u30ec","\u30ed","\u30ef","\u30f0","\u30f1","\u30f2","\u30f3"],"("+b[a]+")"):
b=="a"||b=="\u3042"||b=="lower-latin"||b=="hiragana"?(b=["\u3042","\u3042","\u3044","\u3046","\u3048","\u304a","\u304b","\u304d","\u304f","\u3051","\u3053","\u3055","\u3057","\u3059","\u305b","\u305d","\u305f","\u3061","\u3064","\u3066","\u3068","\u306a","\u306b","\u306c","\u306d","\u306e","\u306f","\u3072","\u3075","\u3078","\u307b","\u307e","\u307f","\u3080","\u3081","\u3082","\u3084","\u3086","\u3088","\u3089","\u308a","\u308b","\u308c","\u308d","\u308f","\u3090","\u3091","\u3092","\u3093"],"("+
b[a]+")"):b=="\u30a4"||b=="katakana-iroha"?(b=["\u30a4","\u30a4","\u30ed","\u30cf","\u30cb","\u30db","\u30d8","\u30c8","\u30c1","\u30ea","\u30cc","\u30eb","\u30f2","\u30ef","\u30ab","\u30e8","\u30bf","\u30ec","\u30bd","\u30c4","\u30cd","\u30ca","\u30e9","\u30e0","\u30a6","\u30f0","\u30ce","\u30aa","\u30af","\u30e4","\u30de","\u30b1","\u30d5","\u30b3","\u30a8","\u30c6","\u30a2","\u30b5","\u30ad","\u30e6","\u30e1","\u30df","\u30b7","\u30f1","\u30d2","\u30e2","\u30bb","\u30b9"],"("+b[a]+")"):b=="\u3044"||
b=="hiragana-iroha"?(b=["\u3044","\u3044","\u308d","\u306f","\u306b","\u307b","\u3078","\u3068","\u3061","\u308a","\u306c","\u308b","\u3092","\u308f","\u304b","\u3088","\u305f","\u308c","\u305d","\u3064","\u306d","\u306a","\u3089","\u3080","\u3046","\u3090","\u306e","\u304a","\u304f","\u3084","\u307e","\u3051","\u3075","\u3053","\u3048","\u3066","\u3042","\u3055","\u304d","\u3086","\u3081","\u307f","\u3057","\u3091","\u3072","\u3082","\u305b","\u3059"],"("+b[a]+")"):b=="I"||b=="upper-roman"?(b=["I",
"I","II","III","IV","V","VI","VII","VIII","IX","X","XI","XII","XIII","XIV","XV","XVI","XVII","XVIII","XIX","XX"],"("+b[a]+")"):b=="i"||b=="lower-roman"?(b=["i","i","ii","iii","iv","v","vi","vii","viii","ix","x","xi","xii","xiii","xiv","xv","xvi","xvii","xviii","xix","xx"],"("+b[a]+")"):b=="1"||b=="decimal"||b=="\u4e00"||b=="cjk-ideographic"||b=="\u58f1"?a<=10?(b=b=="\u58f1"?["\u58f1","\u58f1","\u5f10","\u53c2","\u56db","\u4f0d","\u516d","\u4e03","\u516b","\u4e5d","\u62fe"]:["\u4e00","\u4e00","\u4e8c",
"\u4e09","\u56db","\u4e94","\u516d","\u4e03","\u516b","\u4e5d","\u5341"],"("+b[a]+")"):"("+a+")":""},appendHTML:function(a,b){var c="";a==null&&(a="");if((b||this.process.isBreakable)&&this.process.columnHTML!="")if(this.isWritingModeReady&&!this.isMultiColumnReady||!this.process.isMultiColumnEnabled){if(c=b?this.columnComplement():this.columnComplement(this.process.columnHTML+a),b||this.process.config.width<this.getWidth(c))b||(c=this.columnComplement()),this.process.content+='<div class="taketori-col" style="'+
this.rotatedBlockAdditionalCSSText(this.process.config.height,this.process.config.width,this.process.config.gap,this.process.config.multiColumnEnabled)+'">'+c+"</div>",this.process.columnCount++,(b||this.process.config.columnCount&&this.process.config.columnCount==this.process.columnCount)&&this.containerBreak()}else if(this.process.config.contentHeight&&this.process.config.contentWidth){if(c=b?this.columnComplement():this.columnComplement(this.process.columnHTML+a),b||this.hasToBreak(c))b||(c=this.columnComplement()),
this.process.content+=this.process.config.columnCount&&this.process.config.columnCount>1?'<div class="taketori-col taketori-multi-column" style="-moz-column-width:'+this.process.config.height+"px;-webkit-column-width:"+this.process.config.height+"px;column-width:"+this.process.config.height+"px;-moz-column-count:"+this.process.config.columnCount+";-webkit-column-count:"+this.process.config.columnCount+";column-count:"+this.process.config.columnCount+";-moz-column-gap:"+this.process.config.gap+"px;-webkit-column-gap:"+
this.process.config.gap+"px;column-gap:"+this.process.config.gap+"px;"+this.rotatedBlockAdditionalCSSText(this.process.config.contentHeight,this.process.config.contentWidth,0,!0)+'">'+c+"</div>":'<div class="taketori-col" style="'+this.rotatedBlockAdditionalCSSText(this.process.config.contentHeight,this.process.config.contentWidth)+'">'+c+"</div>",this.containerBreak()}else if(b)this.process.content=document.createElement("div"),this.setMultiColumnStyle(this.process.content),this.process.content.innerHTML=
this.columnComplement(),this.containerBreak(),this.setMultiColumnWidth(this.process.target.firstChild);this.process.columnHTML+=a},columnComplement:function(a){var b=!1,c="";a==null?(c=this.process.columnHTML+(this.process.noCJK>1?"</span>":""),b=!0):c=a+(this.process.noCJK?"</span>":"");if(b){this.process.columnHTML="";this.process.width=0;if(this.process.noCJK)this.process.noCJK=1;if(this.process.latin)this.process.latin=1}for(var a="",d=this.process.openTagsHTML,f=!0,g=this.process.closeTags.length-
1;g>=0;g--){var h=this.process.closeTags[g],i=RegExp("<"+h+"(?!\\w)[^>]*>\\s*$");c.search(i)==-1?a+="</"+h+">":a==""&&(c=c.replace(i,""),h=="li"&&(f=!1))}if(b){this.process.openTagsHTML=this.process.openTags.join("");if(f)this.process.openTagsHTML=this.process.openTagsHTML.replace(/ data-marker=".*?"/g,"");g=0;for(b=this.process.listStart.length;g<b;g++)this.process.openTagsHTML=this.process.openTagsHTML.replace(/ start=""/,'start="'+this.process.listStart[g]+'"')}return d+c+a},getCJKClassName:function(a){if(a==
"\u30fc"||a=="\u301c"||a=="\uff5e"||a=="\u2014"||a=="\u2025"||a=="\u2026")return this.process.kinsoku=!0,"cjk cho-on";else if(a=="\u3001"||a=="\uff0c")return this.process.kinsoku=!0,this.process.currentConfig.lang=="ja-jp"?"cjk tou-ten":"cjk";else if(a=="\u3002"||a=="\uff0e")return this.process.kinsoku=!0,this.process.currentConfig.lang=="ja-jp"?"cjk ku-ten":"cjk";else if(a.search(/^[\u3041\u3043\u3045\u3047\u3049\u3063\u3083\u3085\u3087\u308E\u30A1\u30A3\u30A5\u30A7\u30A9\u30C3\u30E3\u30E5\u30E7\u30EE\u30F5\u30F6]$/)!=
-1)return this.process.kinsoku=!0,"cjk kogaki";else if(a.search(/^[\u3009\u300B\u300D\u300F\u3011\u3015\u3017\u3019\uFF09\uFF3D\uFF5D\uFF60]$/)!=-1)return this.process.kinsoku=!0,"kakko";else if(a.search(/^[\u3008\u300A\u300C\u300E\u3010\u3014\u3016\u3018\uFF08\uFF3B\uFF5B\uFF5F]$/)!=-1)return"kakko";else{if(a.search(/^[\u2030\u2103\u2109\u3012\u3005\u309D\u309E\u30FB\u30FD\u30FE\uFF01\uFF03\uFF04\uFF20\uFFE5\uFF1A\uFF1B\uFF1F]$/)!=-1)this.process.kinsoku=!0;return"cjk"}},kinsokuShori:function(a){if(this.process.kinsoku)this.process.columnHTML=
this.process.columnHTML.replace(/(<span(?!\w)[^>]*class="cjk[^>]*>.<\/span>)$/,""),RegExp.$1&&(a='<span class="kinsoku">'+RegExp.$1+a+"</span>"),this.process.kinsoku=null;return a},complement:function(){this.appendHTML("",!0)},containerBreak:function(){if(typeof this.process.config.onbreak=="function")this.process.config.onbreak(this);else this._containerBreak()},_containerBreak:function(){if(this.process.target){this.removeClipboard();if(!this.process.target.taketori)this.process.target.taketori=
{};if(!this.process.config.contentWidth||!this.process.config.contentHeight||!this.process.done){var a=this.process.target.innerHTML;this.setTaketoriClassName(this.process.target);if(typeof this.process.content=="object")this.process.target.innerHTML="",this.process.target.appendChild(this.process.content);else{this.process.target.innerHTML=this.process.content;var b=this.process.target.firstChild,c=this,d=this.process.config.width,f=this.process.config.gap;setTimeout(function(){if(c.isWritingModeReady){if(b.clientHeight<
b.scrollHeight)b.style.height=b.scrollHeight+"px"}else if(b.clientWidth<b.scrollWidth){var a=b.scrollWidth;b.style.width=a+"px";c.fixMargin(b,a,d,f,c.process.config.multiColumnEnabled)}},600)}if(this.process.config.contentWidth&&this.process.config.contentHeight)this.process.done=!0;this.process.content="";this.process.target.taketori.ttb=!0;this.process.target.taketori.alt=a;this.process.target.taketori.config=this.configClone(this.process.currentConfig);this.process.target.taketori.clientWidth=
this.process.target.clientWidth;this.process.target.taketori.windowHeight=this.windowHeight}this.makeClipboard(this.process.target)}},fixMargin:function(a,b,c,d,f){d||(d=0);if(this.isWritingModeReady){if(d)f?a.style.marginBottom=d+"px":a.style.paddingBottom=d+"px"}else if(a.style.marginTop="-"+c+"px",a.style.marginRight=c-b-d+"px",a.style.marginBottom=b+d+"px",a.style.marginLeft=0,!f&&d)a.style.paddingRight=d+"px"},refresh:function(){if(this.isLegacy)return this;this.init();for(var a=0,b=this.targetElements.length;a<
b;a++){var c=this.targetElements[a];if(c&&c.taketori&&c.taketori.alt&&c.taketori.ttb&&(c.clientWidth!=c.taketori.clientWidth||c.taketori.windowHeight!=this.windowHeight))if(this.setCurrentConfig(c,c.taketori.config),this.process.isBreakable)this.toggle(c,!0,!0),this.make(c,!0);else{var d=c.firstChild,f;if(d){if(this.process.isMultiColumnEnabled)d.style.overflow="auto";if(c.clientWidth!=c.taketori.clientWidth)c.taketori.clientWidth=c.clientWidth,this.isWritingModeReady?d.style.width=this.process.config.width+
"px":d.style.height=this.process.config.width+"px";if(c.taketori.windowHeight!=this.windowHeight){if(this.process.isMultiColumnEnabled)f=this.process.config.height,d.style.MozColumnWidth=f+"px",d.style.webkitColumnWidth=f+"px",d.style.OColumnWidth=f+"px",d.style.columnWidth=f+"px";else if(this.isWritingModeReady){if(d.style.height=this.process.config.height+"px",d.clientHeight<d.scrollHeight)d.style.height=d.scrollHeight+"px"}else if(f=this.process.config.height,d.style.width=f+"px",d.clientWidth<
d.scrollWidth)f=d.scrollWidth,d.style.width=f+"px";c.taketori.windowHeight=this.windowHeight}this.process.isMultiColumnEnabled?(this.isWritingModeReady?d.style.height=this.process.config.height+"px":d.style.width=this.process.config.height+"px",this.setMultiColumnWidth(d)):this.isWritingModeReady||this.fixMargin(d,f,this.process.config.width,this.process.config.gap,this.process.config.multiColumnEnabled)}}}},toggle:function(a,b,c,d){if(this.isLegacy||this.isVerticalTextElement(a)||b!=null&&(b&&(!a.taketori||
!a.taketori.ttb)||!b&&a.taketori&&a.taketori.ttb))return this;this.init();a.taketori&&a.taketori.alt&&(a.taketori.ttb||a.clientWidth==a.taketori.clientWidth&&a.taketori.windowHeight==this.windowHeight)?(b=a.innerHTML,a.innerHTML=a.taketori.alt,a.taketori.ttb?this.removeTaketoriClassName(a):(this.setTaketoriClassName(a),c=!0),c?(a.taketori.alt=(d||this.config.cacheDisabled)&&a.taketori.ttb?null:b,a.taketori.ttb=a.taketori.ttb?!1:!0,a.taketori.clientWidth=a.clientWidth,a.taketori.windowHeight=this.windowHeight):
(this.removeTarget(a),a.taketori=null)):(this.appendTarget(a),this.make(a,!1));return this},clear:function(a){this.toggle(a,!0,!0,!0)}};
;(function(){if(!("undefined"==typeof Muse||"undefined"==typeof Muse.assets)){var a=function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]==b)return c;return-1}(Muse.assets.required,"taketori.js");if(-1!=a){Muse.assets.required.splice(a,1);for(var a=document.getElementsByTagName("meta"),b=0,c=a.length;b<c;b++){var d=a[b];if("generator"==d.getAttribute("name")){"2015.1.2.344"!=d.getAttribute("content")&&Muse.assets.outOfDate.push("taketori.js");break}}}}})();
